to_drop = ['architecturalstyletypeid',
            'airconditioningtypeid',
            'architecturalstyletypeid',
            'basementsqft',
            'buildingclasstypeid',
            'decktypeid',
            'threequarterbathnbr',
            'finishedfloor1squarefeet',
            'finishedsquarefeet6',
            'finishedsquarefeet12',
            'finishedsquarefeet15',
            'finishedsquarefeet13',
            'finishedsquarefeet50',
            'fips',
            'fireplaceflag',
            'fullbathcnt',
            'garagetotalsqft',
            'hashottuborspa',
            'heatingorsystemtypeid',
            'poolsizesum',
            'pooltypeid10',
            'pooltypeid2',
            'pooltypeid7',
            'propertycountylandusecode',
            'propertylandusetypeid',
            'propertyzoningdesc',
            'rawcensustractandblock',
            'censustractandblock',
            'roomcnt',
            'storytypeid',
            'typeconstructiontypeid',
            'yardbuildingsqft17',
            'yardbuildingsqft26',
            'taxdelinquencyflag',
            'taxdelinquencyyear']


